Добавлены интерфейсы IDataParser и ITimeParser
Boo24/liquid-log pull request #2
Opened 2018-10-14 20:28 UTC by Boo24

@d0k1 @ykalemi @etitov

2018-10-16 05:29 UTC, etitov approved these changes

2018-10-16 05:29 UTC, etitov commented on src/main/java/ru/naumen/sd40/log/parser/parsers/timeParsers/TopTimeParser.java
> +public class TopTimeParser implements ITimeParser {
можно было просто изменить ru.naumen.sd40.log.parser.TopParser либо выполнить команду _git mv_ для сохранения истории куда какая логика перетекла

2018-10-16 05:29 UTC, etitov commented
Задание выполнено

2018-10-16 06:36 UTC, ykalemi requested changes

2018-10-16 06:36 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/timeParsers/TopTimeParser.java
> +        return time;
Нет, я всё-таки считаю, что поведение изменилось и это надо проверить.
TopParser - парсит многострочный лог. Значение времени, в отличие от других логов, есть не в каждой строке, а в одной строке на несколько последующих. Поэтому оно должно сохраняться пока не встретим следующее время.

Пример лога будет в канале.

2018-10-16 20:41 UTC, Boo24 commented on src/main/java/ru/naumen/sd40/log/parser/parsers/timeParsers/TopTimeParser.java
> +        return time;
@ykalemi @etitov поправила

2018-10-18 11:57 UTC, ykalemi approved these changes
Отличная идея с handler-ами, благодаря этому все timeParser-ы являются stateless, т.е. не хранят ни какого состояния.
Есть пара косметических замечаний, которые было бы неплохо исправить.

2018-10-18 11:57 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/dataParsers/BaseDataHandler.java
> +    public abstract void handleLine(String line) throws ParseException;
может, переместить в интерфейс?

2018-10-18 11:57 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/dataParsers/ChunkHandler.java
> +        long time = timeParser.parseTime(line);
я бы переделал на protected getter, обращаться к полю напрямую - не очень красиво. Но это вкусовщина

2018-10-22 16:43 UTC, merged