hw4
Boo24/liquid-log pull request #3
Opened 2018-10-24 06:14 UTC by Boo24

@d0k1 @ykalemi @etitov

2018-10-25 07:57 UTC, etitov commented
посмотрю

2018-10-25 17:03 UTC, ykalemi requested changes

2018-10-25 17:03 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/InfluxDBClient.java
> +    private InfluxDAO storage = null;
в исходном коде был какой-то смысл разделения на storage и finalStorage (final было потому что перед переменной стоял модификатор final, и эту переменную можно было использовать в inner class). Сейчас это не имеет смысла

2018-10-25 17:03 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/InfluxDBClient.java
> +    private void Save(long k, DataSet set){
в Java принято использовать lowerCamelCase для именования методов

2018-10-25 17:03 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/InfluxDBClient.java
> +    public DataSet get(long key) {
еще момент по поводу стиля: принято сначала писать static методы, потом поля класса и конструктор, потом public, потом protected и private методы. Суть в том, что человек привык читать сверху вниз, поэтому вначале хочется видеть те методы, которые обозначают интерфейс класса.

2018-10-25 17:03 UTC, ykalemi commented on src/test/java/ru/naumen/sd40/log/parser/InfluxDbClientTests.java
> +public class InfluxDbClientTests {
Я хочу чтобы вы написали еще такой тест: представьте что в файле с логом всего две строки, у которых будут разные ключи. Надо вызвать InfluxDBClient.get и проверить, что все строки будут сохранены

2018-10-25 21:09 UTC, Boo24 commented
@ykalemi

2018-10-26 06:09 UTC, Boo24 commented
Потому что при текущей реализации объекты сохраняются в бд только когда пришел новый ключ, т.е. в логах появилось новое время, значит, последний объект нужно сохранить явно, т.к. после его ключа другого не появится

2018-10-26 06:51 UTC, ykalemi commented
Но там ведь даже flush делается, который должен сохранить второй элемент?

2018-10-26 06:56 UTC, Boo24 commented
Не понимаю. Где дальше?

2018-10-26 07:24 UTC, ykalemi commented
Я там в коде уже прокомментировал, что не в тот метод посмотрел. Всё равно не понимаю, почему нужно вызвать get два раза для одного и того же ключа.

Я, если что, про тест mustReturnDifferentValuesWhenDifferentKeys. Может, это опечатка всё же?

2018-10-26 08:03 UTC, Boo24 commented
@ykalemi  Оу, да, это действительно опечатка

2018-10-26 10:08 UTC, ykalemi approved these changes
Всё остальное - ок. Можно пофиксить и мерджить

2018-10-30 15:23 UTC, merged