Hw 9
Boo24/liquid-log pull request #6
Opened 2018-11-26 18:13 UTC by Boo24

@d0k1 @ykalemi @etitov

2018-11-26 18:14 UTC, Boo24 commented
Хм, запушила в новую ветку, но получилось с коммитами из предыдущей :(
К этому дз относится только последний

2018-11-27 07:27 UTC, ykalemi requested changes
Это даже будет работать, но я считаю, что вы немного переборщили. По сути, сейчас большое количество бинов стали @RequestScope, хотя почти все из них являются синглтонами. Идея была в том, что только TimeParser будет создаваться на каждый запрос, а сейчас почти все бины создаются на каждый запрос.

2018-11-28 07:54 UTC, Boo24 commented
@ykalemi Сделала @RequestScope на метод create, проверила, TimeParser создается на каждый запрос

2018-11-28 12:44 UTC, ykalemi reviewed
В вашем конкретном случае, возможно, нет необходимости навешивать аннотации `@RequestScope` (в текущем виде они просто бесполезны).
Предлагаю тогда остановиться на варианте, когда есть фабрики (Creator-ы), которые создают TimeParser-ы.

2018-11-28 12:44 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/timeParsers/TopTimeParserCreator.java
> +    @RequestScope
На самом деле эта аннотация никак не используется. Здесь не отмечено, что возвращаемый объект является bean-ом. Поэтому просто при каждом вызове происходит создание TimeParser через конструктор. Ну т.е. dependency injection никак не используется.

2018-11-28 12:54 UTC, Boo24 commented on src/main/java/ru/naumen/sd40/log/parser/parsers/timeParsers/TopTimeParserCreator.java
> +    @RequestScope
Убрала

2018-11-28 13:09 UTC, ykalemi approved these changes
ок
(но мерждить всё равно придётся только после предыдущего PR)

2018-12-04 15:24 UTC, merged